config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :words do
    resources :definitions
  end

  root 'site#index'

end

app/models/definition.rb
class Definition < ActiveRecord::Base
  belongs_to :word
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
  	user_type=="admin"
  end

end

app/models/word.rb
class Word < ActiveRecord::Base
	validates :name, :language, presence: true
	has_many :definitions
	accepts_nested_attributes_for :definitions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
		before_filter :authenticate_user!, except: [:index]
		add_breadcrumb "words", :words_path
	def index
		add_breadcrumb "definitions", word_definitions_path

		@word = Word.find params[:word_id]
		@definitions = @word.definitions.all

	end
	def new
		add_breadcrumb "new", new_word_definition_path
		@word = Word.find params[:word_id]
		@definition = @word.definitions.new
	end
	def create
		@word = Word.find params[:word_id]
		@definition = @word.definitions.new entry_params

		if @definition.save
			redirect_to action: 'index', controller:'definitions'
		else
			render 'error'
		end
	end
	def show
		@word = Word.find params[:word_id]

		@definition = @word.definitions.find params[:id]
	end

	def edit
		@word = Word.find params[:word_id]
		@definition = @word.definitions.find params[:id]

	end

	def update
		@word = Word.find params[:word_id]
		@definition = @word.definitions.find params[:id]
		if @definition.update_attributes entry_params
			redirect_to action: 'index', controller: 'definitions', id: @definition.id
			flash[:notice] = 'definition edited succesfully!'
		else
			flash[:alert] = 'Something failed'
			render 'edit'
		end
	end

	def destroy
		@word = Word.find params[:word_id]

		@definition = @word.definitions.find params[:id]
		@definition.destroy
		redirect_to action: 'index', controller: 'definitions', id: @definition.id
	end


	private

	def entry_params
		params.require(:definition).permit(:text, :origin, :category, :video, :example)
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def index
	end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
	  before_filter :authenticate_user!, except: [:index]
		  add_breadcrumb "home", :root_path
  
	def index
		@words = Word.order(name: :asc)
		@words_name = @words.map(&:name)
		gon.words = @words_name
		@words_id = @words.map(&:id)
		gon.words_id= @words_id
		@alphabet = ("a".."z").to_a


		add_breadcrumb "words", words_path
	end
	def new
		@word = Word.new
		 @word.definitions << Definition.new
		 add_breadcrumb "new", new_word_path
	end
	def create
		@word = Word.new entry_params

		if @word.save
			redirect_to action: 'index', controller:'words'
		else
			flash[:alert] = 'Something failed'
			render 'new'
		end
	end
	def show
		@word = Word.find params[:id]
	end

	def edit
		@word = Word.find params[:id]

	end

	def update
		@word = Word.find params[:id]
		if @word.update_attributes entry_params
			redirect_to action: 'index', controller: 'words', id: @word.id
			flash[:notice] = 'Word edited succesfully!'
		else
			flash[:alert] = 'Something failed'
			render 'edit'
		end
	end

	def destroy
		@word = Word.find params[:id]
		@word.destroy
		redirect_to action: 'index', controller: 'words', id: @word.id
	end


	private

	def entry_params
		params.require(:word).permit(:name, :language, definitions_attributes: [:origin, :text, :video, :category, :example])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/definitions/edit.html.erb
<%= form_for [@word, @definition] do |f| %>
	<%= f.label :text %>
	<%= f.text_field :text %>
	<br>
	<%= f.label :video %>
	<%= f.text_field :video %>
	<br>
	<%= f.label :origin %>
	<%= f.text_field :origin %>
	<br>
	<%= f.label :category %>
	<%= f.text_field :category %>
	<br>
	<%= f.label :example %>
	<%= f.text_field :example %>
	<br>

	<%= f.submit 'Edit' %>
<% end %>

app/views/definitions/error.html.erb
ERROR

app/views/definitions/index.html.erb
<%= render_breadcrumbs %>
<h1> <%= @word.name %></h1>
<h2> definitions</h2>

<ul>
<% @definitions.each do |definition| %>

<li><%= definition.text %></li>
<%= link_to('edit definition', edit_word_definition_path(id:definition.id)) %>
<%= link_to('delete definition', word_definition_path(id:definition.id), :method => :delete) %>

<% end %>
</ul>

app/views/definitions/new.html.erb
<%= render_breadcrumbs %>

<%= form_for [@word, @definition] do |f| %>
	<%= f.label :origin %>
	<%= f.text_field :origin %>
	<br> 
	<%= f.label :text %>
	<%= f.text_field :text %>
	<br>
	<%= f.label :video %>
	<%= f.text_field :video %>
	
	<br>
	<%= f.label :category %>
	<%= f.text_field :category %>
	<br>
	<%= f.label :example %>
	<%= f.text_field :example %>
	<br>

	<%= f.submit 'Save' %>
<% end %>

app/views/definitions/show.html.erb
<%= @word %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Erasmus</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all'%>

  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>
</div>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/words/edit.html.erb
<%= form_for [@word] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :language %>
	<%= f.text_field :language %>
	<br>

	<%= f.submit 'Edit' %>
<% end %>

app/views/words/index.html.erb


<%= render_breadcrumbs %>
<h1> TÉRMINOS</h1>

<% @alphabet.each do |letter|  %>
	<button class = 'letter'> <%= letter %></button>

<% end %>
<%= button_to('Crear Palabra',new_word_path, :method => :get) %>

<ul>
<% @words.each do |word| %>

<li><%= link_to( word.name, word_definitions_path(word.id)) %></li>
<%= link_to('editar término', edit_word_path(word.id)) %>
<%= link_to('eliminar término',word_path(word.id), :method => :delete) %>


<% end %>
</ul>
<div id = 'alph'>  </div>










app/views/words/new.html.erb
<%= render_breadcrumbs %>

<%= form_for [@word] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :language %>
	<%= f.select :language, %w[Inglés Español Francés Alemán Italiano Finés Sueco Rumano Portugués], {multiple: true} %>
	<br>
	<%= f.fields_for :definitions do |definition_builder| %>
	<fieldset>
	<%= definition_builder.label :origin %>
	<%= definition_builder.text_field :origin %>
	<br> 
	<%= definition_builder.label :text %>
	<%= definition_builder.text_field :text %>
	<br>
	<%= definition_builder.label :video %>
	<%= definition_builder.text_field :video %>
	
	<br>
	<%= definition_builder.label :category %>
	<%= definition_builder.text_field :category %>
	
	<br>
	<%= definition_builder.label :example %>
	<%= definition_builder.text_field :example %>
	</fieldset>
	<% end %>

	<%= f.submit 'Guardar' %>
<% end %>